adjust offlineScoreAPI
LiteLDev/LiteLoader pull request #1020
Opened 2023-01-17 15:12 UTC by kkj9333

## Description
Resolve https://github.com/LiteLDev/LiteLoaderBDS/issues/1014
Removed exception report
adjusted offlineScoreAPI

PR DESCRIPTION
#1014 
## Issues fixed

_None_

2023-01-17 15:18 UTC, ShrBox approved these changes, later dismissed

2023-01-17 15:41 UTC, Jasonzyt requested changes

2023-01-17 15:41 UTC, Jasonzyt commented on LiteLoader/src/llapi/scoreboard/ScoreboardAPI.cpp
>      auto Sid = Global<Scoreboard>->getOrCreateScoreboardId(uuid);
此处命名不规范

2023-01-18 04:34 UTC, kkj9333 commented on LiteLoader/src/llapi/scoreboard/ScoreboardAPI.cpp
>      auto Sid = Global<Scoreboard>->getOrCreateScoreboardId(uuid);
Sid?

2023-01-18 04:44 UTC, StarsDream00 commented on ScriptEngine/src/api/PlayerAPI.cpp
> +            return Local<Value>();
应该是`return {}`？

2023-01-18 05:03 UTC, kkj9333 commented on ScriptEngine/src/api/PlayerAPI.cpp
> +            return Local<Value>();
参考的其他返回空值时的返回值

2023-01-18 05:25 UTC, ShrBox approved these changes

2023-01-18 05:34 UTC, Jasonzyt commented on LiteLoader/src/llapi/scoreboard/ScoreboardAPI.cpp
>      auto Sid = Global<Scoreboard>->getOrCreateScoreboardId(uuid);
variable name should start with lower-case letter

2023-01-18 05:52 UTC, kkj9333 commented on LiteLoader/src/llapi/scoreboard/ScoreboardAPI.cpp
>      auto Sid = Global<Scoreboard>->getOrCreateScoreboardId(uuid);
ok

2023-01-18 09:43 UTC, dreamguxiang approved these changes

2023-01-18 09:46 UTC, merged