fix PlayerAttackEvent::mAttackDamage
LiteLDev/LiteLoader pull request #1079
Opened 2023-02-12 10:07 UTC by ACX66

## Description

fix wrong PlayerAttackEvent::mAttackDamage
add damage value argument to llse ` onAttackEntity  ` event

## Issues fixed

#1050

2023-02-12 11:59 UTC, Jasonzyt submitted a review, later dismissed

2023-02-15 22:18 UTC, Jasonzyt commented
AttackDamage好像是个float，要不改改？把原先的int的damage改名mIntDamage标deprecated，末尾加个float的mDamage

2023-02-16 14:22 UTC, ACX66 commented
> AttackDamage好像是个float，要不改改？把原先的int的damage改名mIntDamage标deprecated，末尾加个float的mDamage

改好了，但之前WangYneos说这会影响ABI稳定..

2023-02-16 14:31 UTC, Jasonzyt requested changes

2023-02-16 14:31 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    float mAttackDamage = false;
int float不要赋bool的初值…

2023-02-16 14:35 UTC, Jasonzyt commented
> > AttackDamage好像是个float，要不改改？把原先的int的damage改名mIntDamage标deprecated，末尾加个float的mDamage
> 
> 改好了，但之前WangYneos说这会影响ABI稳定..

我觉得无所谓，因为以前mIntAttackDamage的值永远都是2，改了之后无非就是mIntAttackDamage变成永远都是0，插件重新编译会有提示的

2023-02-16 14:39 UTC, ACX66 commented on LiteLoader/include/llapi/EventAPI.h
> +    float mAttackDamage = false;
好的，之前那个int赋了个false我以为有什么特殊用意qwq

2023-02-16 14:40 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    float mAttackDamage = false;
> 好的，之前那个int赋了个false我以为有什么特殊用意qwq

显然不合理，都改一下吧

2023-02-16 14:42 UTC, ACX66 commented on LiteLoader/include/llapi/EventAPI.h
> +    float mAttackDamage = false;
> > 好的，之前那个int赋了个false我以为有什么特殊用意qwq
> 
> 显然不合理，都改一下吧

好辽

2023-02-16 14:44 UTC, Jasonzyt approved these changes
有空的话记得改一下llse文档～

2023-02-16 14:46 UTC, ACX66 commented
> 有空的话记得改一下llse文档～

okkk

2023-02-16 14:58 UTC, ShrBox approved these changes

2023-02-16 14:58 UTC, ShrBox commented on LiteLoader/src/llapi/EventAPI.cpp
> +            return (int)ev.mAttackDamage;
It may cause data lost, if `damage` is integer.
But you can add a new variable to PlayerAttackEvent to solve it, just like
但是你可以通过在PlayerAttackEvent中新增新的变量来解决它，就像
```cpp
class PlayerAttackEvent : public EventTemplate<PlayerAttackEvent> {
public:
    Player* mPlayer = nullptr;
    Actor* mTarget = nullptr;
    [[deprecated]] int mIntDamage = false;
    float mAttackDamage = 0;
};
```

2023-02-16 14:58 UTC, ShrBox commented on LiteLoader/src/llapi/EventAPI.cpp
> +            return (int)ev.mAttackDamage;
```suggestion
            ev.mAttackDamage = damage;
            ev.mIntDamage = (int)damage;
            currentAttackingPlayer.player = nullptr;
            currentAttackingPlayer.target = nullptr;
            if (!ev.call()) {
                currentAttackingPlayer.cancelled = true;
                return 0;
            }
            return ev.mAttackDamage;
```

2023-02-16 15:42 UTC, RimuruChan commented
@Jasonzyt 大小改变，如果有插件进行了复制等操作可能导致出现访问无效内存

2023-02-18 12:06 UTC, Jasonzyt commented
> @Jasonzyt 大小改变，如果有插件进行了复制等操作可能导致出现访问无效内存

有更好的办法吗？🤔

2023-02-18 12:07 UTC, RimuruChan commented
> > @Jasonzyt 大小改变，如果有插件进行了复制等操作可能导致出现访问无效内存
> 
> 有更好的办法吗？🤔

非要完美结局的话当然是弃用原来的结构体

2023-02-25 07:59 UTC, Jasonzyt approved these changes

2023-02-25 07:59 UTC, merged

2023-02-25 10:41 UTC, RimuruChan commented
由于现事件系统内存在复制订阅，影响可能有点大

2023-02-25 10:42 UTC, Jasonzyt commented
以前都这么干的，要解决等LL3罢