mod onHopperSearchItem onHopperPushOut
LiteLDev/LiteLoader pull request #1080
Opened 2023-02-12 10:10 UTC by ACX66

## Description

add item object to ` onHopperSearchItem `, ` onHopperPushOut ` event

## Issues fixed

#990

2023-02-12 11:59 UTC, Jasonzyt requested changes

2023-02-12 11:59 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    ItemStack* mItemStack;
这会导致兼容性问题
请在结构体末尾添加成员
如果要修改数据成员类型，请在原来的数据成员前面添加`[[deprecated]]`说明并在结构体末尾添加新成员

2023-02-12 11:59 UTC, Jasonzyt commented on LiteLoader/src/llapi/EventAPI.cpp
> +} HopperState = None;
```suggestion
} hopperState = None;
```

2023-02-12 11:59 UTC, Jasonzyt commented on LiteLoader/src/llapi/EventAPI.cpp
> +Vec3* HopperPos;
```suggestion
Vec3* hopperPos;
```

2023-02-13 13:07 UTC, Jasonzyt requested changes

2023-02-13 13:07 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    bool isMinecart = false;
请在结构体末尾添加新成员

2023-02-13 14:38 UTC, ACX66 commented on LiteLoader/include/llapi/EventAPI.h
> +    bool isMinecart = false;
okkk 好了
之前是想push和search的成员顺序一样来着www

2023-02-15 06:06 UTC, dreamguxiang approved these changes, later dismissed

2023-02-15 22:14 UTC, Jasonzyt submitted a review, later dismissed

2023-02-15 22:14 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    Vec3 mPos;
新增成员加在末尾
此外，[[]]后面加一个空格，deprecated内容参见692行
（你是不是在用你自己配置的clang-format？）

2023-02-16 14:15 UTC, ACX66 commented on LiteLoader/include/llapi/EventAPI.h
> +    Vec3 mPos;
已进行更改

2023-02-16 15:00 UTC, ShrBox submitted a review, later dismissed

2023-02-16 15:00 UTC, ShrBox commented on LiteLoader/include/llapi/EventAPI.h
> +    ItemStack* mItemStack;
```suggestion
    [[deprecated]] BlockInstance mHopperBlock;
    Vec3 mPos;
    int mDimensionId = -1;
    ItemStack* mItemStack;
```

2023-02-26 00:54 UTC, ShrBox approved these changes

2023-02-26 00:59 UTC, dreamguxiang approved these changes

2023-02-26 01:13 UTC, merged

2023-03-05 08:12 UTC, yqs112358 commented
@ACX66 哥们这块是啥情况啊
![image](https://user-images.githubusercontent.com/37969157/222949400-4bb9e8ea-9599-4819-b073-c81d4cf2918a.png)
你确定这样写没问题吗？？？

2023-03-05 08:16 UTC, yqs112358 commented
@dreamguxiang @Jasonzyt 你们有没有认识残雪的，谁去私聊一下

2023-03-05 08:32 UTC, RimuruChan commented
> @ACX66 哥们这块是啥情况啊
> ![image](https://user-images.githubusercontent.com/37969157/222949400-4bb9e8ea-9599-4819-b073-c81d4cf2918a.png)
> 你确定这样写没问题吗？？？

我合并到ll3的时候也想问来着

2023-03-05 08:33 UTC, yqs112358 commented
请尽快回复，到今晚还不回复revert了

2023-03-05 08:37 UTC, ACX66 commented
> @ACX66 哥们这块是啥情况啊 ![image](https://user-images.githubusercontent.com/37969157/222949400-4bb9e8ea-9599-4819-b073-c81d4cf2918a.png) 你确定这样写没问题吗？？？

很抱歉，这处地方我确实没有考虑周全。
是这样的，这个地方恒return true是为了让它在这个if就返回，而不走下面else那部分的代码，否则要拦截此事件就还需要Hook else部分..  事实上下面这部分代码同样是搜索附近的实体，经测试只运行上半部分可以达到同样的效果，但我也担心自己的测试不够严谨。所以如果您发现这会使漏斗产生什么其他不可预料的特性，也只能麻烦您先revert，我后续也会同步尝试改进。
很抱歉给您添麻烦。
![image](https://user-images.githubusercontent.com/104246753/222950049-dcb023ec-c0b2-44e0-9eca-89d692aa2e47.png)

2023-03-05 08:46 UTC, ACX66 commented
> @ACX66 哥们这块是啥情况啊 ![image](https://user-images.githubusercontent.com/37969157/222949400-4bb9e8ea-9599-4819-b073-c81d4cf2918a.png) 你确定这样写没问题吗？？？

或者可以先删除这段代码，影响则是漏斗矿车的pull和push将无法被拦截（之前的版本同样是如此）。事件本身依然可以被监听。

2023-03-05 08:58 UTC, yqs112358 commented
那我们就先把hook这里删除，发一个新版本了，因为有群友看下来发现好像确实会影响矿车的吸取范围
漏斗矿车那边的问题我觉得需要单独开一个issue记录一下，后面想办法修复，比如找新的点位