feat: add get/setTime() get/setWeather() api
LiteLDev/LiteLoader pull request #1087
Opened 2023-02-13 21:18 UTC by ACX66

## Description

feat:
add ` mc.getTime() `, ` mc.setTime() `, ` mc.getWeather() `, ` mc.setWeather() ` function
(不确定这些函数是否应该添加在ServerAPI，如果放的位置不对还请麻烦指出)

## Issues fixed

Close #1082

2023-02-13 23:03 UTC, WangYneos commented on ScriptEngine/src/api/ServerAPI.cpp
> +        logger.error("Wrong Argument");
参数异常请返回给脚本引擎

2023-02-14 13:31 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +        logger.error("Wrong Argument");
抛出引擎异常方法：
`throw script::Exception(content)`

2023-02-14 13:33 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
如没有特别需要，最好不要使用SymCall

2023-02-14 14:37 UTC, ACX66 commented on ScriptEngine/src/api/ServerAPI.cpp
> +        logger.error("Wrong Argument");
好的，已进行更改。

2023-02-14 14:39 UTC, ACX66 commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
ok 去掉了两个SymCall，最后剩的那个在SDK里是MCVAPI，似乎不能直接调用。（还是说可以通过其他方法？）

2023-02-15 11:24 UTC, ShrBox commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
> ok 去掉了两个SymCall，最后剩的那个在SDK里是MCVAPI，似乎不能直接调用。（还是说可以通过其他方法？）

MCVAPI需要还原结构体或补充大小

2023-02-15 11:32 UTC, ShrBox commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
可以参考[这里](https://redbeanw44602.github.io/mcstructure/1.16.201/structure/R.html#random)，不知道过了这么多个版本有没有更改

2023-02-15 13:54 UTC, ACX66 commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
> > ok 去掉了两个SymCall，最后剩的那个在SDK里是MCVAPI，似乎不能直接调用。（还是说可以通过其他方法？）
> 
> MCVAPI需要还原结构体或补充大小

悲 确实是不知道怎么还原或者补充大小 有什么例子嘛qwq

2023-02-15 22:03 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +        int finalTime = SymCall("?projectToTimeOfDay@LevelUtils@@YAHHH@Z", int, int, int)(currentTime, targetTime);
> > > ok 去掉了两个SymCall，最后剩的那个在SDK里是MCVAPI，似乎不能直接调用。（还是说可以通过其他方法？）
> > 
> > 
> > MCVAPI需要还原结构体或补充大小
> 
> 悲 确实是不知道怎么还原或者补充大小 有什么例子嘛qwq

那就先这样吧，~~能跑就行~~

2023-02-15 22:08 UTC, Jasonzyt requested changes

2023-02-15 22:08 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +            newTime = currentTime + targetTime - currentTimeOfDay;
if括号加空格不符合规范

2023-02-15 22:08 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +    int duration, weather = args[0].asNumber().toInt32(); // weather: 0: Clear, 1: Rain, 2: Thunder
最好给duration赋个初值，这是局部变量
```suggestion
    int duration = 0;
    int weather = args[0].asNumber().toInt32(); // weather: 0: Clear, 1: Rain, 2: Thunder
```

2023-02-15 22:08 UTC, Jasonzyt commented on ScriptEngine/src/api/ServerAPI.cpp
> +    if (option == 0)
连续if，建议switch

2023-02-16 14:06 UTC, cryx233 commented on ScriptEngine/src/api/ServerAPI.cpp
> +    if (option == 0)
改好辽

2023-02-16 15:01 UTC, ShrBox approved these changes

2023-02-25 09:37 UTC, dreamguxiang approved these changes

2023-02-25 09:38 UTC, Jasonzyt approved these changes

2023-02-25 09:38 UTC, merged