Fix #991
LiteLDev/LiteLoader pull request #1103
Opened 2023-02-28 15:25 UTC by Tsubasa6848

## Description

Fix #991

PR DESCRIPTION

## Issues fixed
#991 

_None_

2023-02-28 19:38 UTC, Jasonzyt requested changes
另外如果生物被打死了会怎样

2023-02-28 19:38 UTC, Jasonzyt commented on LiteLoader/src/llapi/EventAPI.cpp
> +            auto Health0 = getHealth();
```suggestion
            auto healthBefore = getHealth();
```

2023-02-28 19:38 UTC, Jasonzyt commented on LiteLoader/src/llapi/EventAPI.cpp
> +            auto Health1 = Global<Level>->getEntity(uid)->getHealth();
```suggestion
            auto healthAfter = Global<Level>->getEntity(uid)->getHealth();
```

2023-02-28 21:11 UTC, Tsubasa6848 commented on LiteLoader/src/llapi/EventAPI.cpp
> +            auto Health0 = getHealth();
这个问题我考虑过，但是
"?_hurt@Mob@@MEAA_NAEBVActorDamageSource@@M_N1@Z"
在
?die@Mob@@UEAAXAEBVActorDamageSource@@@Z"
之前就发生了，如果生物死了，获取到生命值是0，这个时候还没有死亡，不受影响。

2023-02-28 21:12 UTC, Tsubasa6848 commented on LiteLoader/src/llapi/EventAPI.cpp
> +            auto Health0 = getHealth();
不过获取实际伤害没有这么麻烦，我重新commit。

2023-02-28 22:03 UTC, Tsubasa6848 commented on LiteLoader/src/llapi/EventAPI.cpp
> +            auto Health0 = getHealth();
我后面重新提交PR

2023-02-28 22:53 UTC, Tsubasa6848 commented
本地构建并且测试了一下，应该没有问题

2023-03-01 11:24 UTC, ShrBox submitted a review, later dismissed

2023-03-01 21:55 UTC, Tsubasa6848 commented
#991 应该是没有问题了
但是这个PR里面 #959 并没有完全修好。
考虑到一个PR只能Link一个issue，我回滚对 #959 的修改，重新开一个分支提交

2023-03-01 23:08 UTC, WangYneos submitted a review, later dismissed

2023-03-02 15:09 UTC, Jasonzyt requested changes
此外，MobHurtEvent涉及插件较多，建议保留兼容性并按照原有逻辑进行处理（尤其是llse），llse改baselib也成，如果cpp实在难搞就算了

2023-03-02 15:09 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    [[deprecated("MobHurtEvent is outdated, please use BeforeMobHurtEvent instead")]]
deprecated位置错误

2023-03-02 15:49 UTC, Tsubasa6848 commented on LiteLoader/include/llapi/EventAPI.h
> +    [[deprecated("MobHurtEvent is outdated, please use BeforeMobHurtEvent instead")]]
deprecated 放哪？

2023-03-02 15:50 UTC, Tsubasa6848 commented on LiteLoader/include/llapi/EventAPI.h
> +    [[deprecated("MobHurtEvent is outdated, please use BeforeMobHurtEvent instead")]]
cpp恐怕不好保留兼容层。
但是LLSE我是保留了原来的事件的

2023-03-04 09:57 UTC, Jasonzyt commented on LiteLoader/include/llapi/EventAPI.h
> +    [[deprecated("MobHurtEvent is outdated, please use BeforeMobHurtEvent instead")]]
类的deprecated放在类头

2023-03-05 12:57 UTC, harry-xi commented
> 此外，MobHurtEvent涉及插件较多，建议保留兼容性并按照原有逻辑进行处理（尤其是llse），llse改baselib也成，如果cpp实在难搞就算了

实际上 改baselib不怎么成，那玩意不做用于nodejs插件
> 我不确定这条信息改如何提供比较合适，但是恰好看见这个然后想起来了就提了一嘴

2023-03-05 21:43 UTC, Jasonzyt commented on ScriptEngine/src/api/EventAPI.cpp
> +            logger.warn("Event 'onMobHurt' is outdated, please use 'onBeforeMobHurt' instead.");
建议删除输出

2023-03-07 04:46 UTC, closed without merging

2023-03-07 04:52 UTC, Tsubasa6848 commented
我和其它PR一样，重新开个分支提交，之前全放develop里面太乱了