Feat #1011
LiteLDev/LiteLoader pull request #1105
Opened 2023-03-01 14:18 UTC by Tsubasa6848

## Description
Feat #1011

PR DESCRIPTION

## Issues fixed
#1011

_None_

2023-03-02 15:11 UTC, Jasonzyt requested changes, later dismissed

2023-03-02 15:11 UTC, Jasonzyt commented on ScriptEngine/src/api/PlayerAPI.cpp
> +        Local<Array> effectlist = Array::newArray();
```suggestion
        Local<Array> effectList = Array::newArray();
```

2023-03-04 01:27 UTC, ShrBox approved these changes

2023-03-04 03:58 UTC, OEOTYAN approved these changes

2023-03-04 03:58 UTC, merged