feat: #991
LiteLDev/LiteLoader pull request #1117
Opened 2023-03-08 20:45 UTC by Tsubasa6848

## Description

feat #991

## Issues fixed
#991

_None_

2023-03-08 21:26 UTC, Jasonzyt commented on LiteLoader/src/llapi/EventAPI.cpp
> +        if (this) {
冗余if语句

2023-03-08 21:59 UTC, Tsubasa6848 commented on LiteLoader/src/llapi/EventAPI.cpp
> +        if (this) {
> 冗余if语句

其实我也觉得那个if是冗余的，只是以前就有我没删，我把它删了吧

2023-03-09 10:19 UTC, OEOTYAN commented
你猜怎么着，之前有人反馈onmobhurt的mob有概率是空指针

2023-03-09 10:47 UTC, RimuruChan requested changes
请注意ABI兼容性问题

2023-03-09 16:09 UTC, Tsubasa6848 commented
> 请注意ABI兼容性问题

兼容性问题，LLSE兼容旧的API，cpp确实不好做，这个更新sdk很容易就改过来了。

2023-03-09 16:09 UTC, Tsubasa6848 commented
> 你猜怎么着，之前有人反馈onmobhurt的mob有概率是空指针

所以说还是把if加回去？

2023-03-09 16:10 UTC, RimuruChan commented
@Tsubasa6848 你把旧的事件去掉了，使用了旧事件的插件将无法加载

2023-03-09 16:10 UTC, OEOTYAN commented
> > 你猜怎么着，之前有人反馈onmobhurt的mob有概率是空指针
> 
> 所以说还是把if加回去？

https://github.com/LiteLDev/LiteLoaderBDS/issues/980 你看看

2023-03-09 16:12 UTC, OEOTYAN commented
别问我为什么this还能是空指针 反正就是有bug讲是空 那就加上呗

2023-03-09 16:12 UTC, Tsubasa6848 commented
> > > 你猜怎么着，之前有人反馈onmobhurt的mob有概率是空指针
> > 
> > 
> > 所以说还是把if加回去？
> 
> #980 你看看

那我等会把if重新加回去吧

2023-03-09 16:14 UTC, Tsubasa6848 commented
> @Tsubasa6848 你把旧的事件去掉了，使用了旧事件的插件将无法加载

LLSE不是保留了吗，cpp这边需要适配SDK不是应该影响不大吗？
如果需要修改，请问我应该怎么保留兼容性？

2023-03-09 16:15 UTC, KobeBryant114514 commented
> 别问我为什么this还能是空指针 反正就是有bug讲是空 那就加上呗

行那等会加回去，不过我确实觉得this不应该是空指针，既然有这个bug那还是加上

2023-03-09 16:19 UTC, RimuruChan commented
@Tsubasa6848 把你去掉的符号补回去，declare补上，before的时候也顺便去call一下之前的event

2023-03-20 04:58 UTC, WillowSauceR commented
> 你猜怎么着，之前有人反馈onmobhurt的mob有概率是空指针

生物死亡时，对应的资源被释放，似乎就会导致this变为空指针？但是总感觉不应该，Actor::_hurt在生物死亡之前被调用，此时生物应该还没有死亡才对。

2023-03-22 03:00 UTC, yqs112358 commented
这个PR怎么样了，OK了莫 @Tsubasa6848 @RimuruChan

2023-03-22 13:57 UTC, RimuruChan commented
其他不清楚，但是ABI不兼容

2023-03-24 10:53 UTC, yqs112358 commented
@Tsubasa6848 是这样，我粗略看了一下，有一个很必要的就是要保证ABI兼容，比如你加新事件的话，首先旧事件的结构体和那个DECLARE_EVENT_DATA得留着，不然就ABI不兼容了
其次在新事件的监听器中应该挑一个去调用旧事件，比如在onBeforeMobHurt中调用onMobHurt，以兼容旧的没有重新编译的插件
你再仔细检查一下相关问题

2023-04-01 17:50 UTC, OEOTYAN commented
蚌 怎么还没好

2023-04-22 03:17 UTC, closed without merging