fix enum error
LiteLDev/LiteLoader pull request #1145
Opened 2023-03-22 13:06 UTC by kkj9333

## Description

PR DESCRIPTION

## Issues fixed

_None_

2023-03-22 13:19 UTC, ShrBox submitted a review, later dismissed

2023-03-22 14:14 UTC, WangYneos requested changes

2023-03-22 14:14 UTC, WangYneos commented on LiteLoader/include/llapi/mc/inc/enums.inc
> +    unkownrecipebook=21,
What's that, 如无法明确解释，请将其注释掉

2023-03-22 15:50 UTC, Jasonzyt commented on LiteLoader/include/llapi/mc/inc/enums.inc
> +    unkownrecipebook=21,
而且不符合命名规范

2023-03-23 01:02 UTC, kkj9333 commented on LiteLoader/include/llapi/mc/inc/enums.inc
> +    unkownrecipebook=21,
ok

2023-03-23 01:16 UTC, kkj9333 commented on LiteLoader/include/llapi/mc/inc/enums.inc
> +    unkownrecipebook=21,
已更改

2023-03-24 10:40 UTC, dreamguxiang approved these changes

2023-03-24 11:16 UTC, merged