feat: add statitics service
LiteLDev/LiteLoader pull request #1476
Opened 2024-02-27 09:46 UTC by ShrBox

## What does this PR do?

Add statitics service

## Which issues does this PR resolve?

Nope

## Checklist before merging

Thank you for your contribution to the repository. 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] Your code follows the code style of this repository (see the wiki)
- [x] You have tested all functions
- [x] You have not used code without license
- [x] You have added statement for third-party code

2024-02-28 07:29 UTC, OEOTYAN commented
真是太屎了 就为这b东西还得加俩库 尤其是uuid最屎 明明有uuid类

2024-02-28 09:53 UTC, RimuruChan requested changes

2024-02-28 09:53 UTC, RimuruChan commented on xmake.lua
> +        "cpp-httplib",
内部依赖，不需要的暴露

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.cpp
> +#include "ll/core/tweak/Statistics.h"
导入应当分组

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.cpp
> +float randomFloat() {
应当使用RandomUtils

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.cpp
> +    static std::random_device              rd;
>  _mc不带随机uuid工具吗？_

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.cpp
> +void InitStatitics() {
不符合命名标准

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.cpp
> +    if (!std::filesystem::exists(plugin::getPluginsRoot() / u8"LeviLamina/data")) {
过长namespace，善用using，以及namespace别名，如 `namespace fs = std::filesystem;`

2024-02-28 09:53 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.h
> +    std::unique_ptr<Impl> impl;
不必要的pimpl封装

2024-02-28 09:53 UTC, RimuruChan commented on xmake.lua
> +add_requires("cpp-httplib", {configs={ssl=true, zlib=true}})
zlib可能需要重写禁用系统库，否则有msys2的环境会出问题

2024-02-28 10:21 UTC, ShrBox commented on src/ll/core/tweak/Statistics.h
> +    std::unique_ptr<Impl> impl;
源文件里面有个hook用到了

2024-02-28 11:04 UTC, RimuruChan requested changes

2024-02-28 11:04 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.h
> +    std::unique_ptr<Impl> impl;
构造函数static 存一个就行了

2024-02-28 11:05 UTC, RimuruChan commented on src/ll/core/tweak/Statistics.h
> +    std::unique_ptr<Impl> impl;
没懂，这需要pimpl吗，放构造函数static不行吗

2024-02-28 11:06 UTC, ShrBox commented on src/ll/core/tweak/Statistics.h
> +    std::unique_ptr<Impl> impl;
> 没懂，这需要pimpl吗，放构造函数static不行吗

好

2024-02-29 06:37 UTC, RimuruChan approved these changes

2024-02-29 06:37 UTC, merged