Events
LiteLDev/LiteLoader pull request #192
Opened 2022-02-06 07:36 UTC by MCBEPluginModer

Add PlayerBucketFillEvent,PlayerTameEntityEvent and PlayerTargetEntityEvent

2022-02-06 07:38 UTC, MCBEPluginModer commented
Please move to LiteLoader:beta branch.

2022-02-06 07:54 UTC, Jasonzyt requested changes
TOO MANY BUGS
you should PR after the local build and avoid mistakes

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Header/EventAPI.h
> +class PlayerBucketFillEvent : public EventTemplate<ConsoleOutputEvent>
```suggestion
class PlayerBucketFillEvent : public EventTemplate<PlayerBucketFillEvent>
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Header/EventAPI.h
> +class PlayerTameEntityEvent : public EventTemplate<ConsoleOutputEvent>
```suggestion
class PlayerTameEntityEvent : public EventTemplate<PlayerTameEntityEvent>
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Header/EventAPI.h
> +class PlayerTargetEntityEvent : public EventTemplate<ConsoleOutputEvent>
```suggestion
class PlayerTargetEntityEvent : public EventTemplate<PlayerTargetEntityEvent>
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Header/EventAPI.h
> +class PlayerBedEnterEvent : public EventTemplate<ConsoleOutputEvent>
```suggestion
class PlayerBedEnterEvent : public EventTemplate<PlayerBedEnterEvent> 
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +DeclareEventListeners(PlayerBucketFillEvent);
```suggestion
DeclareEventListeners(PlayerBucketFillEvent);
// [Another two events]
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Header/EventAPI.h
> +  Acctor* mActor;
```suggestion
  Actor* mActor;
```

2022-02-06 07:54 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +        ev.mPlayer = &a;
```suggestion
        ev.mPlayer = (Player*)&a;
```

2022-02-06 07:56 UTC, Jasonzyt commented
Please clone your fork repo to your computer and use Visual Studio or CLion to modify your code and build the project.then `git commit&push`

2022-02-06 08:17 UTC, Jasonzyt requested changes

2022-02-06 08:17 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +            return 0;
```suggestion
            return;
```

2022-02-06 08:17 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +        ev.mItemStack = (ItemStack*)&s;
```suggestion
        ev.mItemStack = &s;
```

2022-02-06 08:17 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +            return 0;
```suggestion
            return;
```

2022-02-06 08:17 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +        ev.mActor = act;
```suggestion
        ev.mActor = &act;
```

2022-02-06 08:17 UTC, Jasonzyt commented on LiteLoader/Kernel/EventAPI.cpp
> +            return 0;
Use false is better
```suggestion
            return false;
```

2022-02-06 08:18 UTC, WangYneos commented
Build and test what you wrote

2022-02-06 08:18 UTC, closed without merging

2022-02-06 08:21 UTC, Jasonzyt commented
You can start the actions in your repo

2022-08-30 15:20 UTC, hausemaster3734 commented
Zhenya...