添加Headers
LiteLDev/LiteLoader pull request #396
Opened 2022-05-05 12:32 UTC by MoorCorPa

add request headers

2022-05-05 21:22 UTC, Jasonzyt requested changes

2022-05-05 21:22 UTC, Jasonzyt commented on LiteLoader/Kernel/Utils/NetworkHelper.cpp
> +    Json::Value h;
use nlohmann::json plz
非必要别用jsoncpp（）
```suggestion
    nlohmann::json j;
```

2022-05-05 21:22 UTC, Jasonzyt commented on LiteLoader/Kernel/Utils/NetworkHelper.cpp
> +        if (reader.parse(headers, h))
```suggestion
        h = nlohmann::json::parse(headers)
```

2022-05-06 01:53 UTC, MoorCorPa commented on LiteLoader/Kernel/Utils/NetworkHelper.cpp
> +    Json::Value h;
骚瑞，我是第一次写 c++www

2022-05-06 11:10 UTC, merged

2022-05-06 11:11 UTC, Jaciezyt commented
感谢大佬的贡献！