Add PlayerUseBucket Event
LiteLDev/LiteLoader pull request #746
Opened 2022-08-31 09:06 UTC by quizhizhe

- [x] Add Bucket Event
- [x] Bucket Event Support to LLSE
#335

2022-08-31 09:15 UTC, Jaciezyt reviewed
LLSE documentation is required

2022-08-31 13:32 UTC, quizhizhe commented
经测试发现，没有捕获到装鱼和装牛奶的动作，我分析下看看

2022-09-05 07:05 UTC, Jasonzyt commented
Tip: 如果PR已经完成了，请Ready for review

2022-09-05 07:15 UTC, quizhizhe commented
装牛奶事件还没找到，虽然#335说的是装鱼事件，其实onUseItemOn也监控不到这个，我再挣扎下，实在找不到就这样了

2022-09-08 07:49 UTC, Jaciezyt requested changes

2022-09-08 07:49 UTC, Jaciezyt commented on LiteLoader/Header/EventAPI.h
> + * \~chinese @brief ���¼��������ʹ����Ͱ��
File encoding error, please fix

2022-09-08 07:50 UTC, Jasonzyt approved these changes

2022-09-08 08:00 UTC, Jaciezyt commented
所以这个PR把#335 全部做完了吗

2022-09-08 08:15 UTC, quizhizhe commented
> 所以这个PR把#335 全部做完了吗

做完了，使用桶的都能监控到，也能拦截

2022-09-08 08:16 UTC, merged