新增离线玩家NBT读写API和完善PlayerAteEvent
LiteLDev/LiteLoader pull request #920
Opened 2022-12-02 15:31 UTC by Tsubasa6848

## Description
新增离线玩家NBT读写API  #305 
完善PlayerAteEvent并为LLSE添加该事件  #895 

## Issues fixed by this PR
新增了离线玩家NBT读写API
LIAPI static bool setPlayerNbt(mce::UUID const& uuid, CompoundTag& nbt);
LIAPI static bool setPlayerNbtTags(mce::UUID const& uuid, CompoundTag& data, vector<string> tags);
LIAPI static bool deletePlayerNbt(mce::UUID const& uuid);
LIAPI static std::unique_ptr<CompoundTag> getPlayerNbt(mce::UUID const& uuid);
issue #305

为LLSE添加PlayerAteEvent并改为TInstanceHook
issue #895 

## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-12-02 15:51 UTC, Jasonzyt requested changes
另外请更新LLSE的文档，进行测试以确保可用性（如果已经测试过了当我没说

2022-12-02 15:51 UTC, Jasonzyt commented on LiteLoader/src/llapi/mc/PlayerAPI.cpp
> +    *((void**)&rv) = dlsym("?getPlayer@Level@@UEBAPEAVPlayer@@AEBVUUID@mce@@@Z");
~~bdx时代的写法~~
建议使用
https://github.com/LiteLDev/LiteLoaderBDS/blob/a5eaf6290b0f3836075098148e2a5131746c4f25/LiteLoader/include/llapi/mc/Level.hpp#L1130

2022-12-02 15:51 UTC, Jasonzyt commented on LiteLoader/src/llapi/mc/PlayerAPI.cpp
> +bool deletePlayerNbt(mce::UUID const& uuid){
style: {前要加一个空格
下同（建议使用IDE自带的clang-format工具跑一下

2022-12-02 15:55 UTC, Jasonzyt commented
按#305 的要求，LLSE的API也需要，麻烦大佬看看罢

2022-12-03 03:52 UTC, Tsubasa6848 commented
PlayerAteEvent经测试没有任何问题。
离线NBT的API这部分的代码我再改改，LLSE的适配我会看看（我一般不用LLSE所以说写的时候一般都没给脚本引擎写）

2022-12-04 12:40 UTC, closed without merging

2022-12-05 06:23 UTC, Jasonzyt commented
Duplicate of #929